function exptype = init_exptype()

fields = {'eyetracking', ...
    'isPractice',...
    'isDebug',...
    'isfMRI',...
    'isMSB',...
    'isQuest',...
    'isBB',...
    'isQmini',...
    'exemplar_threshold'};
for i = 1:numel(fields), exptype.(fields{i}) = 0; end
