function BlockText = TC_instructions(screen_name, blocknum, nblocks)

switch screen_name
    case 'loading'
        BlockText = 'Loading ...';
    case 'instructions_overview'
        BlockText = ['INSTRUCTIONS\n\n\n'...
            'In this experiment you will be asked to make judgments about simple images.\n\n'...           
            'You will see images of faces, animals, objects and houses. \n\n'...
            'You will be asked to detect repeating images, indicate the image category \n\n'...
            'and to describe your visual experience.\n\n'...
            'Press any key to continue.']; 
    case 'overview'  
        BlockText = ['The experiment will include the following parts:\n\n\n'...
            '(1) Perception task (~40 min)\n\n'...
            '(2) Color change task (~20 min)\n\n'...
            '(3) One-back visual memory task (~7 min)\n\n'...
            '(4) Resting state (5 min)\n\n'...   
            'You will be able to take mental breaks every 5-10 minutes\n\n\n'...
            'Press any key to continue.']; 
    case 'instructions'
        BlockText = ['INSTRUCTIONS\n\n\n'...
            'In this experiment you will be asked to make judgments about simple images.\n\n'...           
            'You will see images of faces, animals, objects and houses. \n\n'...
            'Afterwards you will be asked to indicate the image category \n\n'...
            'and to describe your visual experience.\n\n'...
            'Press any key to continue.'];
    case 'fixation'
        BlockText = ['In the middle of the screen you can see a fixation cross,\n\n\n\n\n\n\n'...
            'Please always keep your eyes on this cross when you see it.\n\n'...
            'Press any key to continue.'];
    case 'FixationReminder'
        BlockText = ['THANK YOU!\n\n\n\n\n\n\n'...
             'From now on please keep your eyes on the fixation cross\n\n'...
             'Press any key to continue.'];        
         
    case 'rest'  
        BlockText = ['RESTING STATE:\n\n\n'...
            'This is the easiest part! \n\n'...           
            'You will be asked to keep your eyes on the fixation cross.\n\n'...
            'Please do not focus your mind on anything too specific during this time.\n\n'...   
            'Press any key to continue.'];
    case 'ImageExamples'
        BlockText = ['You are now going to see examples of images that will appear in the experiment.\n\n\n\n'...
            'Please make sure you are able to define the category of each image:\n\n'...
            'Face / Object / House / Animal\n\n\n\n'...
            'Press any key to proceed to next image.'];    
	case 'localizer'
        BlockText = ['One-back memory task.\n\n\n\n'...
            'You will see various images appearing on the screen one at a time.\n\n'...
            'You are asked to press any button when you see\n'...
            'two identical images one after another.\n\n\n\n'...
            'Press any key to try this task.'];
    case 'retinotopy'
        BlockText = ['Color change task.\n\n\n\n'...
            'You will be asked to keep your eyes on a center dot, which will alternate in color.\n\n'...
            'Press any key when the color of the dot changes.\n\n'...
            'Please ignore the other shapes presented on the screen.\n\n\n\n'...
            'Press any key to try this task.'];
    case 'MeaningfulExperience'
        BlockText = ['You will also be asked if you had any meaningful visual experience.\n\n'...
            'For example: if you saw an animal, or only part of an animal, \n'...
            'as long as you have a sense of the image''s identity - please answer ''yes''.\n\n'...
            'There will be cases where you will see only a noisy glimpse of light or simply nothing.\n'...
            'If this is the case, the experience is not meaningful - please answer ''no''.'];
    case 'Guess'  
        BlockText = ['PERCEPTION TASK.\n\n\n'....
            'Next, the images will be presented very briefly. \n\n'...
            'If you don''t see anything - this is normal, \n'...
            'just try your best to guess the correct image category. \n\n'...
            'If you need to make a guess, please make a genuine guess.\n' ...
            'That is, don''t use a systematic strategy for your guesses, '...
            'like always pressing "1" \n' ...
            'or always pressing the opposite of what you pressed last.\n\n'...
            'No matter your visual experience, please answer every question. '];
        
    case 'Summary'
        BlockText = ['Summary of perception task:\n\n\n\n'...
            '1. Fixation cross\n\n'...
            '2. Image presentation\n\n'...
            '3. Category: Guess if unsure\n\n'...
            '4. Visual experience: Yes or No\n\n'...
            '5. Always respond\n\n'];
        
    case 'practiceStart'
        BlockText = ['Now you have some time to practice.\n\n'...
            'Press any key to begin.'];   
    case 'practiceEnd'
        BlockText = ['You finished your practice session.\n\n\n'...          
            'THANK YOU!\n\nPress any key to exit.'];  
    case 'ThresholdRelax'
        BlockText = ['You can relax now.\n\n\n'...
            'It might take a while before the next part.'...
            '\n\n'];
    case 'nextBlock'
        BlockText = ['Feel free to take a break. Next block: ' blocknum '/' nblocks '\n\n\n\n'...
            'Press any key to continue'];
    case 'ThresholdEnd'
        BlockText = ['THANK YOU!\n\n\n\n'...
            'Press any key to continue'];    
    case 'PdetectionQ'
        BlockText = ['Meaningful visual experience: \n\n\n\n\n ',...
            'Yes            No\n\n\n ',...
            ' 2              3\n'];
    case 'PorientationQ'
         BlockText = ['Face       House      Animal     Object\n\n\n', ...
                        '1          2          3          4'];        
end
end

